/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#615e57",
        "inverse-primary": "#cbc6bd",
        "surface-tint": "#615e57",
        "on-secondary-fixed": "#231919",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        "inverse-on-surface": "#f2f0f0",
        "error": "#ba1a1a",
        "surface-dim": "#dbd9d9",
        "secondary-fixed-dim": "#d5c2c2",
        "surface-bright": "#fbf9f8",
        "tertiary": "#735c00",
        "secondary-container": "#eedbdb",
        "inverse-surface": "#303030",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed-variant": "#504444",
        "on-surface-variant": "#49463f",
        "secondary": "#695b5b",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#f1dede",
        "surface-container-highest": "#e4e2e2",
        "on-secondary-container": "#6d5f5f",
        "on-tertiary-fixed-variant": "#574500",
        "outline-variant": "#cbc6bc",
        "tertiary-container": "#ffeec6",
        "on-primary-fixed-variant": "#494640",
        "tertiary-fixed-dim": "#e9c349",
        "on-primary-container": "#706c65",
        "on-background": "#1b1c1c",
        "on-primary": "#ffffff",
        "primary-fixed": "#e7e2d9",
        "surface-container": "#efeded",
        "primary-container": "#f5efe6",
        "outline": "#7b776e",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e2e2",
        "background": "#fbf9f8",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#cbc6bd",
        "tertiary-fixed": "#ffe088",
        "surface": "#fbf9f8",
        "on-primary-fixed": "#1d1b16",
        "surface-container-low": "#f5f3f3",
        "surface-container-high": "#eae8e7",
        "on-tertiary-container": "#846900"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-edge": "clamp(16px, 4vw, 64px)",
        "unit-sm": "8px",
        "element-gap": "16px",
        "unit-lg": "clamp(16px, 3vw, 32px)",
        "section-gap": "clamp(48px, 8vw, 120px)",
        "container-max": "1440px",
        "gutter": "24px",
        "unit-xs": "4px",
        "unit-md": "16px"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Noto Serif", "serif"],
        "headline-sm": ["Noto Serif", "serif"],
        "display-lg": ["Noto Serif", "serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-md": ["clamp(14px, 1.5vw, 16px)", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["clamp(15px, 1.8vw, 18px)", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["clamp(20px, 3.5vw, 32px)", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["clamp(16px, 2.5vw, 24px)", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["clamp(24px, 5vw, 48px)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["clamp(10px, 1.2vw, 12px)", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
